name: 'Create issues on PR merge'
description: 'Looks for "Breaks:" in a PR comment and opens an issue when found'
inputs:
  repo-token:
    description: 'Token for the repository. Can be passed in using {{ secrets.GITHUB_TOKEN }}'
    required: true
runs:
  using: 'node16'
  main: 'index.js'
