#!/bin/sh

ESM_ENABLED="This Ubuntu 12.04 ESM system is actively receiving extended security updates
from Canonical:
 * http://www.ubuntu.com/esm"

ESM_DISABLED="This Ubuntu 12.04 LTS system is past its End of Life, and is no longer
receiving security updates.  To protect the integrity of this system, it’s
critical that you enable Extended Security Maintenance updates:
 * http://www.ubuntu.com/esm"

if `apt-cache policy | grep -q 'esm\.ubuntu\.com'`; then
    echo "$ESM_ENABLED"
else
    echo "$ESM_DISABLED"
fi

