#!/bin/bash -e
# shellcheck disable=SC2039,SC1090

SCRIPTNAME=$(basename "$0")

# system details
SERIES=${SERIES:-$(lsb_release -cs)}
KERNEL_VERSION=${KERNEL_VERSION:-$(uname -r)}
ARCH=${ARCH:-$(uname -m)}
# system files
FSTAB=${FSTAB:-"/etc/fstab"}
CPUINFO=${CPUINFO:-"/proc/cpuinfo"}
KEYRINGS_DIR=${KEYRINGS_DIR:-"/usr/share/keyrings"}
APT_AUTH_FILE=${APT_AUTH_FILE:-"/etc/apt/auth.conf"}
APT_KEYS_DIR=${APT_KEYS_DIR:-"/etc/apt/trusted.gpg.d"}
APT_METHOD_HTTPS=${APT_METHOD_HTTPS:-"/usr/lib/apt/methods/https"}
CA_CERTIFICATES=${CA_CERTIFICATES:-"/usr/sbin/update-ca-certificates"}
# system binaries
SNAPD=${SNAPD:-"/usr/lib/snapd/snapd"}
APT_HELPER=${APT_HELPER:-"/usr/lib/apt/apt-helper"}

load_modules() {
    local script_dir modules_dir
    script_dir=$(dirname "$0")
    if [ "$script_dir" = "/usr/bin" ]; then
        modules_dir="/usr/share/ubuntu-advantage-tools/modules"
    else
        modules_dir="${script_dir}/modules"
    fi

    local module
    for module in "$modules_dir"/*.sh; do
        . "$module"
    done
}

load_modules

print_status() {
    local esm_status
    if esm_is_enabled; then
        esm_status="enabled"
    else
        esm_status="disabled"
        is_supported_series "$ESM_SUPPORTED_SERIES" || esm_status="disabled (not available)"
    fi
    echo "esm: $esm_status"

    local livepatch_status livepatch_output
    if livepatch_is_enabled; then
        livepatch_status="enabled"
        livepatch_output=$(canonical-livepatch status)
    else
        livepatch_status="disabled"
        is_supported_series "$LIVEPATCH_SUPPORTED_SERIES" || livepatch_status="disabled (not available)"
    fi
    echo "livepatch: $livepatch_status"
    if [ "$livepatch_output" ]; then
        # shellcheck disable=SC2001
        echo "$livepatch_output" | sed 's/^/  /'  # indent output
    fi

    local fips_status
    if fips_is_enabled; then
        fips_status="enabled"
    else
        fips_status="disabled"
        is_supported_series "$FIPS_SUPPORTED_SERIES" || fips_status="disabled (not available)"
    fi
    echo "fips: $fips_status"
}


usage() {
    cat >&2 <<EOF
usage: ${SCRIPTNAME} <command> [parameters]

This is a tool that facilitates access to some of Canonical's
Ubuntu Advantage offerings.

Currently available are:
- Ubuntu Extended Security Maintenance archive (https://ubuntu.com/esm)
- Canonical Livepatch Service (https://www.ubuntu.com/server/livepatch)
- Canonical FIPS 140-2 Certified Modules

Commands:
 version                   show the tool version
 status                    show current status of Ubuntu Advantage offerings
 enable-esm <token>        enable the ESM repository
 disable-esm               disable the ESM repository
 enable-livepatch <token>  enable the Livepatch service
 disable-livepatch [-r]    disable the Livepatch service. With "-r", the
                           canonical-livepatch snap will also be removed
 enable-fips <token>       enable the FIPS PPA repository and install,
                           configure and enable FIPS certified modules
 disabe-fips               currently not supported
EOF
}


case "$1" in
    enable-livepatch)
        check_user
        livepatch_check_support
        token="$2"
        if ! livepatch_validate_token "$token"; then
            error_msg "Invalid or missing Livepatch token"
            error_msg "Please visit https://ubuntu.com/livepatch to obtain a Livepatch token."
            exit 3
        fi
        livepatch_enable "$token"
        ;;

    disable-livepatch)
        check_user
        livepatch_check_support
        remove_snap="no"
        if [ -n "$2" ]; then
            if [ "$2" = "-r" ]; then
                remove_snap="yes"
            else
                error_msg "Unknown option \"$2\""
                usage
                exit 1
            fi
        fi
        livepatch_disable "$remove_snap"
        ;;

    is-livepatch-enabled)
        # no root needed
        livepatch_is_enabled
        ;;

    enable-esm)
        check_user
        esm_check_support
        token="$2"
        if ! validate_user_pass_token "$token"; then
            error_msg 'Invalid token, it must be in the form "user:password"'
            exit 3
        fi
        esm_enable "$token"
        ;;

    disable-esm)
        check_user
        esm_check_support
        esm_disable
        ;;

    is-esm-enabled)
        # no root needed
        esm_is_enabled
        ;;

    enable-fips)
        check_user
        fips_check_support
        token="$2"
        if ! validate_user_pass_token "$token"; then
            error_msg 'Invalid token, it must be in the form "user:password"'
            exit 3
        fi

        enable_fips "$token"
        ;;

    disable-fips)
        if fips_is_enabled; then
            not_supported 'Disabling FIPS'
        else
            error_msg 'FIPS is not enabled.'
            exit 1
        fi
        ;;

    is-fips-enabled)
        # no root needed
        fips_is_enabled
        ;;

    status)
        print_status
        ;;

    version)
        package_version ubuntu-advantage-tools
        ;;

    *)
        usage
        exit 1
        ;;
esac
