.TH "UBUNTU-ADVANTAGE" "1" "29 March 2019" "Canonical Ltd." "Ubuntu Advantage"


.SH NAME
ubuntu-advantage \- Manage Ubuntu Advantage services from Canonical


.SH SYNOPSIS
.BR "ua" " <command> [<args>]"
.br
.BR "ubuntu-advantage" " <command> [<args>]"


.SH DESCRIPTION
Ubuntu Advantage is a collection of services offered by Canonical to
Ubuntu users. The Ubuntu Advantage command line tool is used to attach
a system to an Ubuntu Advantage contract to then enable and disable
services from Canonical. The available commands and services are
described in more detail below.


.SH COMMANDS
.TP
.BR "attach" " [token]"
Connect an Ubuntu Advantage support contract to this machine.

The optional \fItoken\fR parameter can be obtained from
https://auth.contracts.canonical.com/. When no \fItoken\fR is provided,
users are prompted for their Ubuntu SSO login credentials to
https://login.ubuntu.com, which will enable an individual contract on
the system.

.TP
.BR "disable" " [cc|cis-audit|esm|fips|fips-updates|livepatch]"
Disable this machine's access to an Ubuntu Advantage support services.

.TP
.BR "enable" " [cc|cis-audit|esm|fips|fips-updates|livepatch]"
Activate and configure this machine's access to an Ubuntu Advantage
services.

.TP
.BR "status" " [--format=table|json]"
Report current status of Ubuntu Advantage services on system.

This shows whether this machine is attached to an Ubuntu Advantage
support contract. When attached, the report includes the specific
support contract details including contract name, expiry dates, and the
status of each service on this system.

Each service status line has three columns:

.BR "name" ":"
name of the service

.BR "availability" ":"
whether the contract entitles use of this service. Possible values are:
none or entitled

.BR "status" ":"
whether the service is activated on this machine.
Possible values are: active, inactive, or n/a

.TP
.B version
Show version of the Ubuntu Advantage package.

.TP
.B detach
Remove the Ubuntu Advantage support contract from this machine. This
also disables all enabled services that can be.


.SH SERVICES
.TP
.B "Common Criteria EAL2 Provisioning (cc)"
Enables and install the common criteria artifacts.

The artifacts include a configure script, a tarball with additional
packages, and post install scripts. The artifacts will be installed in
/usr/lib/common-criteria directory. The evaluated configuration guide
and README instructions on how to set up a system to be Common Criteria
compliant are available in /usr/share/doc/ubuntu-commoncriteria
directory.

.TP
.B "CIS Audit (cis-audit)"
Enables and installs the CIS Audit artifacts.

.TP
.B "Extended Security Maintenance (esm)"
Extended Security Maintenance ensures the ongoing security and
integrity of Ubuntu Long-term support (LTS) systems through Ubuntu
Advantage for Infrastructure.

See https://ubuntu.com/esm for more information.

.TP
.B "FIPS 140-2 certified modules (fips)"
Install, configure, and enable FIPS 140-2 certified modules.

After successfully enabling FIPS, the system MUST be rebooted. Failing
to reboot will result in the system not running the updated FIPS
kernel.

Disabling FIPS is not currently supported.

.TP
.B "FIPS 140-2 certified modules with updates (fips-updates)"
Install, configure, and enable FIPS 140-2 certified modules with
updates. Enabling FIPS with updates will take the system out of FIPS
compliance as the updated modules are not FIPS certified.

After successfully enabling FIPS with updates, the system MUST be
rebooted. Failing to reboot will result in the system not running the
updated FIPS kernel.

Disabling FIPS with updates is not currently supported.


.TP
.B "Livepatch Service (livepatch)"
Automatically apply critical kernel patches without rebooting. Reduces
downtime, keeping your Ubuntu LTS systems secure and compliant.

See https://www.ubuntu.com/server/livepatch for more information.


.SH COPYRIGHT
Copyright (C) 2019 Canonical Ltd.
