.TH UBUNTU-ADVANTAGE 1  "28 April 2017" "" ""
.SH NAME
ubuntu-advantage \- Enable or disable Ubuntu Advantage offerings from
Canonical.
.SH SYNOPSIS
.B ubuntu-advantage
<command> [parameters]
.SH DESCRIPTION
This tool is used to enable or disable specific Ubuntu Advantage offerings
from Canonical. The available modules and their commands are described below.
It must be run with root privileges.
.TP
.B
status
Show the status of Ubuntu Advantage offerings.
.SH ESM (Extended Security Maintenance)
Ubuntu Extended Security Maintenance archive. See https://ubuntu.com/esm for
more information.
.TP
.B
enable-esm \fItoken\fR
Enable the ESM repository. The \fItoken\fR argument must be in the form
"user:password".
.TP
.B
disable-esm
Disable the ESM repository.

.SH Livepatch (Canonical Livepatch Service)
Managed live kernel patching. For more information, visit
https://www.ubuntu.com/server/livepatch
.TP
.B
enable-livepatch \fI<token>\fR
Enable the Livepatch service. The \fItoken\fR can be obtained by visiting
https://ubuntu.com/livepatch
.TP
.B
disable-livepatch \fR[\fB\-r\fR]
Disable the Livepatch service. If the \fB\-r\fR option is given, the
canonical-livepatch snap will be removed after the sevice is disabled.
.SH EXIT STATUS
.TP
.B
0
Command succeded
.TP
.B
1
Invalid command or option
.TP
.B
2
Current user is not root
.TP
.B
3
Invalid or missing token when enabling a service
.TP
.B
4
The requested service not supported on the current Ubuntu release
.TP
.B
5
Current kernel is too old to support Snaps (required for the Livepatch service)
.TP
If apt commands run by the tool fail, the exit status from apt is returned.
