name: 'Release Checklist'
description: "Add release checklist to the PR"
inputs:
  repo-token:
    description: 'Token for the repository. Can be passed in using {{ secrets.GITHUB_TOKEN }}'
    required: true
runs:
  using: 'node16'
  main: 'index.js'
