#!/usr/bin/python3
import argparse
import os
import sys

from uaclient.config import MOTD_CACHE_FILE, MOTD_ESM_CACHE_FILE, UAConfig
from uaclient import status
from uaclient import util


def main():
  cfg = UAConfig()
  motd_summary = status.get_motd_summary(cfg, esm_only=True)
  cache_file = MOTD_ESM_CACHE_FILE if esm_only else MOTD_CACHE_FILE
  if motd_summary:
      util.write_file(cache_file, motd_summary)
  else:
      if os.path.exists(MOTD_CACHE_FILE):
          os.path.unlink(MOTD_CACHE_FILE)

if __name__ == '__main__':
    sys.exit(main())
