#!/usr/bin/python3

import sys

from jinja2 import Template

input_file = sys.argv[1]
output_file = sys.argv[2]
kwargs = {}

# key=value pairs in the command-line
if len(sys.argv) > 3:
    kwargs = {arg.split("=")[0]:arg.split("=")[1] for arg in sys.argv[3:]}

t = Template(open(input_file, "r").read())
output = t.render(**kwargs)

with open(output_file, "w") as f:
    f.write(output)

