#!/bin/sh -e

configure_apt_sources() {
    python3 -c '
    from uaclient.apt import configure_default_apt_sources, migrate_apt_sources

configure_default_apt_sources()
migrate_apt_sources()
'
}

configure_apt_sources()

#DEBHELPER#

