#!/bin/sh

set -e


remove_apt_files() {
    python3 -c '
from uaclient.apt import migrate_apt_sources

migrate_apt_sources(clean=True)
'

}

case "$1" in
    purge|remove)
        remove_apt_files
        ;;
esac

#DEBHELPER#

exit 0

