#!/bin/sh

set -e


remove_apt_files() {
    python3 -c '
from uaclient.apt import clean_apt_sources

clean_apt_sources()
'

}

case "$1" in
    purge|remove)
        remove_apt_files
        ;;
esac

#DEBHELPER#

exit 0

