contract_token: C14KB4gcF3P9mnr5iXm6LiaCmtbmvP
contract_token_staging: C1qJwsWbT7diQH4FJk4jFnnnDLTMv
contract_token_staging_expired: C12USoWtMQvL6y11hK4yh8JWAm1L4F
contract_token_staging_expired_sometimes: C13Uw5zXKApXiBgjLu6RtWvNgYwpQu

contract_staging_service_account_username: pro-client-ci
contract_staging_service_account_password: rz9+svq35s3gBEhX6AZ45ZoKW7ublfvynFzBfPJx

landscape_registration_key: skyward-frail-earthling
landscape_api_access_key: CAPRC4IKOV7DIX9TI5XD
landscape_api_secret_key: UQ/EuXFG/9x3zICTI+OuJn43d0ExWuE+6LjxG1fi
