contract_schema = {
    "activityInfo": {
        "activityID": "",
        "activityPingInterval": 0,
        "activityToken": "",
        "resources": [""],
    },
    "availableResources": [
        {
            "available": False,
            "name": "",
            "description": "",
            "presentedAs": "",
        }
    ],
    "machineToken": "",
    "machineTokenInfo": {
        "accountInfo": {
            "createdAt": "2019-06-14T06:45:50Z",
            "id": "",
            "name": "",
            "type": "",
            "userRoleOnAccount": "",
            "externalAccountIDs": [{"origin": "", "IDs": [""]}],
        },
        "contractInfo": {
            "createdAt": "2021-05-21T20:00:47Z",
            "createdBy": "",
            "effectiveTo": "9999-12-31T00:00:00Z",
            "effectiveFrom": "9999-12-31T00:00:00Z",
            "id": "",
            "items": [
                {
                    "contractID": "",
                    "created": "2021-05-21T20:05:20Z",
                    "effectiveFrom": "0001-01-01T00:00:00Z",
                    "effectiveTo": "9999-12-31T00:00:00Z",
                    "externalIDs": None,
                    "id": 34426,
                    "lastModified": "0001-01-01T00:00:00Z",
                    "metric": "",
                    "reason": "",
                    "value": 0,
                    "purchaseID": "",
                    "productListingID": "",
                    "disabled": False,
                    "disabledExplanation": "",
                    "subscriptionID": "",
                    "period": "",
                }
            ],
            "name": "",
            "products": [""],
            "resourceEntitlements": [
                {
                    "type": "",
                    "entitled": False,
                    "affordances": {
                        "architectures": [""],
                        "presentedAs": "",
                        "series": [""],
                        "kernelFlavors": [""],
                        "minKernelVersion": "",
                        "tier": "",
                        "supportLevel": "",
                    },
                    "directives": {
                        "additionalPackages": [""],
                        "aptURL": "",
                        "aptKey": "",
                        "suites": [""],
                        "server": "",
                        "remoteServer": "",
                        "caCerts": "",
                        "snapChannel": "",
                        "machineCountStrategy": "",
                        "pypiURL": "",
                        "url": "",
                    },
                    "obligations": {
                        "enableByDefault": False,
                        "additionalProperties": [""],
                    },
                    "series": {
                        "bionic": {
                            "affordances": {
                                "architectures": [""],
                                "presentedAs": "",
                                "series": [""],
                                "kernelFlavors": [""],
                                "minKernelVersion": "",
                                "tier": "",
                                "supportLevel": "",
                            },
                            "obligations": {
                                "enableByDefault": False,
                                "additionalProperties": "",
                            },
                            "directives": {
                                "additionalPackages": [""],
                                "aptURL": "",
                                "aptKey": "",
                                "suites": [""],
                                "server": "",
                                "remoteServer": "",
                                "caCerts": "",
                                "snapChannel": "",
                                "machineCountStrategy": "",
                                "pypiURL": "",
                                "url": "",
                            },
                        },
                        "focal": {
                            "affordances": {
                                "architectures": [""],
                                "presentedAs": "",
                                "series": [""],
                                "kernelFlavors": [""],
                                "minKernelVersion": "",
                                "tier": "",
                                "supportLevel": "",
                            },
                            "obligations": {
                                "enableByDefault": False,
                                "additionalProperties": "",
                            },
                            "directives": {
                                "additionalPackages": [""],
                                "aptURL": "",
                                "aptKey": "",
                                "suites": [""],
                                "server": "",
                                "remoteServer": "",
                                "caCerts": "",
                                "snapChannel": "",
                                "machineCountStrategy": "",
                                "pypiURL": "",
                                "url": "",
                            },
                        },
                        "xenial": {
                            "affordances": {
                                "architectures": [""],
                                "presentedAs": "",
                                "series": [""],
                                "kernelFlavors": [""],
                                "minKernelVersion": "",
                                "tier": "",
                                "supportLevel": "",
                            },
                            "obligations": {
                                "enableByDefault": False,
                                "additionalProperties": "",
                            },
                            "directives": {
                                "additionalPackages": [""],
                                "aptURL": "",
                                "aptKey": "",
                                "suites": [""],
                                "server": "",
                                "remoteServer": "",
                                "caCerts": "",
                                "snapChannel": "",
                                "machineCountStrategy": "",
                                "pypiURL": "",
                                "url": "",
                            },
                        },
                        "jammy": {
                            "affordances": {
                                "architectures": [""],
                                "presentedAs": "",
                                "series": [""],
                                "kernelFlavors": [""],
                                "minKernelVersion": "",
                                "tier": "",
                                "supportLevel": "",
                            },
                            "obligations": {
                                "enableByDefault": False,
                                "additionalProperties": "",
                            },
                            "directives": {
                                "additionalPackages": [""],
                                "aptURL": "",
                                "aptKey": "",
                                "suites": [""],
                                "server": "",
                                "remoteServer": "",
                                "caCerts": "",
                                "snapChannel": "",
                                "machineCountStrategy": "",
                                "pypiURL": "",
                                "url": "",
                            },
                        },
                        "trusty": {
                            "affordances": {
                                "architectures": [""],
                                "presentedAs": "",
                                "series": [""],
                                "kernelFlavors": [""],
                                "minKernelVersion": "",
                                "tier": "",
                                "supportLevel": "",
                            },
                            "obligations": {
                                "enableByDefault": False,
                                "additionalProperties": "",
                            },
                            "directives": {
                                "additionalPackages": [""],
                                "aptURL": "",
                                "aptKey": "",
                                "suites": [""],
                                "server": "",
                                "remoteServer": "",
                                "caCerts": "",
                                "snapChannel": "",
                                "machineCountStrategy": "",
                                "pypiURL": "",
                                "url": "",
                            },
                        },
                        "precise": {
                            "affordances": {
                                "architectures": [""],
                                "presentedAs": "",
                                "series": [""],
                                "kernelFlavors": [""],
                                "minKernelVersion": "",
                                "tier": "",
                                "supportLevel": "",
                            },
                            "obligations": {
                                "enableByDefault": False,
                                "additionalProperties": "",
                            },
                            "directives": {
                                "additionalPackages": [""],
                                "aptURL": "",
                                "aptKey": "",
                                "suites": [""],
                                "server": "",
                                "remoteServer": "",
                                "caCerts": "",
                                "snapChannel": "",
                                "machineCountStrategy": "",
                                "pypiURL": "",
                                "url": "",
                            },
                        },
                    },
                    "overrides": [
                        {
                            "selector": {"series": "", "cloud": ""},
                            "directives": {
                                "additionalPackages": [""],
                                "aptURL": "",
                                "aptKey": "",
                                "suites": [""],
                                "server": "",
                                "remoteServer": "",
                                "caCerts": "",
                                "snapChannel": "",
                                "machineCountStrategy": "",
                                "pypiURL": "",
                                "url": "",
                            },
                            "obligations": {
                                "enableByDefault": False,
                                "additionalProperties": "",
                            },
                            "affordances": {
                                "architectures": [""],
                                "presentedAs": "",
                                "series": [""],
                                "kernelFlavors": [""],
                                "minKernelVersion": "",
                                "tier": "",
                                "supportLevel": "",
                            },
                        }
                    ],
                }
            ],
            "specificResourceEntitlements": [],
            "activeMachines": {
                "activeMachines": 0,
                "hours": 0,
                "maximumTrackingReached": False,
            },
            "allowances": [{"metric": "", "value": 0}],
            "renewals": [],
            "origin": "",
        },
        "machineId": "",
        "expires": "2019-06-14T06:45:50Z",
    },
    "resourceTokens": [{"token": "", "type": ""}],
}
