name: Markdown style checks

on:
  workflow_call:
  push:
    branches:
    - docs
    paths:
    - 'docs/**'   # Only run on changes to the docs directory
  pull_request:
    branches:
    - '*'
    paths:
    - 'docs/**'   # Only run on changes to the docs directory

jobs:
  markdown-lint:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - name: Create venv
      working-directory: "docs"
      run: make install
    - name: Lint markdown
      working-directory: "docs"
      run: make lint-md
