---

name: Release Checks

on:
  pull_request:
    branches:
      - release

jobs:
  release-changelog-bug-refs:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: cd ./.github/actions/release-changelog-bug-refs && npm install
      - name: Check for bug references
        uses: ./.github/actions/release-changelog-bug-refs
        id: release-changelog-bug-refs
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
